from ssh.supportedOperSys.base_os import BaseOs

window_commands = {
    "Accept keyboard input to a batch file": "choice",
    "Active Directory ACLs": "dsacls",
    "Active Directory Bulk Modify": "admodcmd",
    "Active Directory Domain Services management": "ntdsutil",
    "Add a message to the Windows event log": "eventcreate",
    "Add items to Active Directory (user group computer)": "dsadd",
    "Add or list users to/from a CSV file": "addusers",
    "Address Resolution Protocol": "arp",
    "Associate a path with a drive letter": "subst",
    "Automated cleanup of Temp files, recycle bin": "cleanmgr",
    "Background Intelligent Transfer Service": "bitsadmin",
    "Baseline Security Analyzer": "mbsacli",
    "Batch process multiple files": "forfiles",
    "BitLocker Drive Encryption": "manage-bde",
    "Call one batch program from another •": "call",
    "Change Directory - move to a specific Folder •": "chdir",
    "Change Registry Permissions": "regini",
    "Change Terminal Server Session properties": "change",
    "Change account password": "pspasswd",
    "Change colors of the CMD window •": "color",
    "Change file and folder permissions": "xcacls",
    "Change file attributes": "attrib",
    "Change file extension associations •": "assoc",
    "Change file permissions": "cacls",
    "Change file timestamps": "touch",
    "Change the active console Code Page": "chcp",
    "Change the command prompt •": "prompt",
    "Check Disk - check and repair disk problems": "chkdsk",
    "Check free disk space": "freedisk",
    "Check the NTFS file system": "chkntfs",
    "Clear event logs, enable/disable/query logs": "wevtutil",
    "Clear the screen •": "cls",
    "Client-side caching (Offline Files)": "csccmd",
    "Comment / Remark •": "::",
    "Communicate with another host using the TELNET protocol": "telnet",
    "Compare the contents of two files or sets of files": "windiff",
    "Compare two files": "fc",
    "Compress files or folders on an NTFS partition": "compact",
    "Compress one or more files": "compress",
    "Conditionally perform a command •": "if",
    "Configure IP": "ipconfig",
    "Configure Network Interfaces, Firewall & Remote access": "netsh",
    "Configure a system device COM/LPT/CON": "mode",
    "Configure power settings": "powercfg",
    "Connect to a Hyper-V Virtual Machine": "vmconnect",
    "Console input": "con",
    "Control the visibility of environment variables •": "setlocal",
    "Convert a FAT drive to NTFS": "convert",
    "Copy STDIN to the Windows clipboard": "clip",
    "Copy files and folders": "xcopy",
    "Copy one or more files to another location •": "copy",
    "Create .CAB files": "makecab",
    "Create a new Directory •": "md",
    "Create a self extracting ZIP file archive": "iexpress",
    "Create a symbolic link (linkd) •": "mklink",
    "Create a windows shortcut (.LNK file)": "shortcut",
    "Create or repair a system partition": "bcdboot",
    "Defragment hard drive": "defrag",
    "Delay processing of a batch file/command": "timeout",
    "Delete a Directory •": "rmdir",
    "Delete a folder and all subfolders": "deltree",
    "Delete one or more files •": "erase",
    "Delete user profiles": "delprof",
    "Deployment Image Servicing and Management": "dism",
    "Device Manager Command Line Utility": "devcon",
    "Direct a batch program to jump to a labelled line •": "goto",
    "Directory Service Management": "dsmgmt",
    "Disconnect a Remote Desktop Session": "tsdiscon",
    "Disk Administration": "diskpart",
    "Display Resultant Set of Policy information": "gpresult",
    "Display a disk label •": "vol",
    "Display a list of files and folders •": "dir",
    "Display disk usage": "diruse",
    "Display file version no. VirusTotal status & timestamp": "sigcheck",
    "Display installed device drivers": "driverquery",
    "Display locale information (reskit)": "nlsinfo",
    "Display message on screen •": "echo",
    "Display networking statistics (NetBIOS over TCP/IP)": "nbtstat",
    "Display networking statistics (TCP/IP)": "netstat",
    "Display or set a search path for executable files •": "path",
    "Display or set the date •": "date",
    "Display or set the system time •": "time",
    "Display output, one screen at a time": "more",
    "Display the Media Access Control (MAC) address": "getmac",
    "Display the SID of a computer or a user": "psgetsid",
    "Display the contents of a text file •": "type",
    "Display the current Date and Time": "now",
    "Display the host name of the computer": "hostname",
    "Display the status of ports and services": "portqry",
    "Display version information •": "ver",
    "Display volume shadow copy backups + writers/providers": "vssadmin",
    "Display, set, or remove session environment variables •": "set",
    "Domain Manager": "netdom",
    "Edit Service Principal Names": "setspn",
    "Edit a disk label": "label",
    "Edit command line, recall commands, and create macros": "doskey",
    "Edit file and folder Permissions, Ownership and Domain": "subinacl",
    "Edit user account rights": "ntrights",
    "Encrypt or Decrypt files/folders": "cipher",
    "End a running process": "tskill",
    "End localisation of the environment in a batch file •": "endlocal",
    "Event log records": "psloglist",
    "Execute a program under a different user account": "runas",
    "Execute process remotely": "psexec",
    "File Server Resource Manager Disk quotas": "dirquota",
    "File Transfer Protocol": "ftp",
    "File and Volume utilities": "fsutil",
    "File extension file type associations •": "ftype",
    "Format a disk": "format",
    "Get domain, browser and PDC info": "browstat",
    "Graphical display of folder structure": "tree",
    "Import or Export Active Directory data": "csvde",
    "Import or export registry settings": "regedit",
    "Is the current user a member of a group": "ifmember",
    "Kill processes by name or process ID": "pskill",
    "List detailed information about processes": "pslist",
    "List information about a system": "psinfo",
    "List or edit a file share or print share": "share",
    "List running applications and services": "tasklist",
    "List system configuration": "systeminfo",
    "Load PerfMon performance counters": "lodctr",
    "Local Group Policy Object utility": "lgpo",
    "Locate and display files in a directory tree": "where",
    "Log a user off": "logoff",
    "Log the date and time in a file": "logtime",
    "Lookup the registration record for a domain": "whois",
    "Manage Boot Configuration Data": "bcdedit",
    "Manage DNS servers": "dnscmd",
    "Manage Hyper-V network bindings": "nmbind",
    "Manage MiniFilter drivers": "fltmc",
    "Manage Performance Monitor logs": "logman",
    "Manage RAS connections": "rasphone",
    "Manage a volume mount point": "mountvol",
    "Manage certification authority (CA) files and services": "certutil",
    "Manage network resources": "net",
    "Manage stored usernames/passwords": "cmdkey",
    "Manipulate network routing tables": "route",
    "Measure network performance": "psping",
    "Microsoft Windows Installer": "msiexec",
    "Modify items in Active Directory (user group computer)": "dsmod",
    "Modify network bindings": "nvspbind",
    "Monitor an application for CPU spikes": "procdump",
    "Monitor and log system activity to the Windows event log": "sysmon",
    "Monitor internal packet propagation and packet drop reports": "pktmon",
    "Move a user from one domain to another": "moveuser",
    "Move an Active Directory Object": "dsmove",
    "Move files from one folder to another •": "move",
    "Name server lookup": "nslookup",
    "Network Location Test (AD)": "nltest",
    "Online Help": "help",
    "Open Windows Explorer": "explorer",
    "OpenSSH remote login client": "ssh",
    "Output the current UserName and domain": "whoami",
    "Print a text file": "print",
    "Print queue Backup/Recovery": "printbrm",
    "Query Process Display processes": "qprocess",
    "Query Session Display all sessions (TS/Remote Desktop)": "qwinsta",
    "Query TermServer List all servers (TS/Remote Desktop)": "qappsrv",
    "Query User Display user sessions (TS/Remote Desktop)": "quser",
    "Query or display open files": "openfiles",
    "Quit the current script/routine and set an errorlevel •": "exit",
    "Record comments (remarks) in a batch file •": "rem",
    "Recover a damaged file from a defective disk": "recover",
    "Register or unregister a DLL": "regsvr32",
    "Registry: Read, Set, Export, Delete keys and values": "reg",
    "Remove items from Active Directory": "dsrm",
    "Rename a file or files •": "ren",
    "Replace files that are in use by the OS": "inuse",
    "Replace or update one file with another": "replace",
    "Request certificate from a certification authority": "certreq",
    "Return to a previous directory saved by PUSHD •": "popd",
    "Robust File and Folder Copy": "robocopy",
    "Run WinPE commands": "wpeutil",
    "Run a DLL command (add/remove print connections)": "rundll32",
    "Run a command under a different user account": "shellrunas",
    "Run one or more scripts": "scriptrunner",
    "Save and then change the current directory •": "pushd",
    "Schedule a command to run at a specific time": "schtasks",
    "Search Active Directory (user group computer)": "dsquery",
    "Search for ANSI and UNICODE strings in binary files": "strings",
    "Search for a text string in a file": "find",
    "Search for strings in files": "findstr",
    "Send a message": "msg",
    "Send email from the command line": "mapisend",
    "Service Control": "sc",
    "Session\tDelete a Remote Desktop Session": "reset",
    "Set environment variables": "setx",
    "Set the window title for a CMD.EXE session •": "title",
    "Share a folder or a printer": "rmtshare",
    "Shift the position of batch file parameters •": "shift",
    "Show files opened remotely": "psfile",
    "Show permissions for a user": "perms",
    "Show the mapping between logical & physical processors": "coreinfo",
    "Show the space used in folders": "diskuse",
    "Shutdown or reboot a computer": "psshutdown",
    "Shutdown the computer": "shutdown",
    "Software Licensing Management": "slmgr",
    "Sort input": "sort",
    "Specify which display to use and how to use it": "displayswitch",
    "Start a new CMD shell": "cmd",
    "Start a program, command or batch file •": "start",
    "Start | RUN commands": "run",
    "Store, list or extract files in an archive": "tar",
    "Suspend processes": "pssuspend",
    "Suspend processing of a batch file •": "pause",
    "System File Checker": "sfc",
    "System Information": "msinfo32",
    "Take ownership of a file": "takeown",
    "Task list with full path": "tlist",
    "Terminal Server Connection/Remote Desktop Protocol(RDP)": "mstsc",
    "Test a network connection": "ping",
    "Time Service": "w32tm",
    "Time Zone Utility": "tzutil",
    "Trace route plus network latency and packet loss": "pathping",
    "Trace route to a remote host": "tracert",
    "Transfer data from or to a server": "curl",
    "Uncompress CAB files": "extract",
    "Update Group Policy settings": "gpupdate",
    "Upgrade device Edition/Product Key": "changepk",
    "Verify that files have been saved •": "verify",
    "View and control services": "psservice",
    "View items in Active Directory (user group computer)": "dsget",
    "Volume Shadow Copy Service": "diskshadow",
    "WMI Commands": "wmic",
    "Wait for or send a signal": "waitfor",
    "Wait for x seconds": "sleep",
    "Who's logged on (locally or via resource sharing)": "psloggedon",
    "Windows Backup Admin": "wbadmin",
    "Windows Backup folders to tape": "ntbackup",
    "Windows Event Collector Utility": "wecutil",
    "Windows Package Manager (coming May 2021)": "winget",
    "Windows Performance Recorder": "wpr",
    "Windows Remote Management": "winrm",
    "Windows Remote Shell": "winrs",
    "Windows Terminal": "wt",
    "Windows Update": "wuauclt",
    "Windows Update Standalone Installer": "wusa",
    "Write Performance Monitor data to a log file": "typeperf"
}


class WindowsOs(BaseOs):

    def __init__(self, device_id):
        self.__package_manager = ""
        self.OS = "windows"
        super().__init__('windows', device_id)

    def get_users(self):
        """
        centos related get users
        :return:
        """
        command = "net user"
        result = self.execute_command(command)
        return result


    def get_loggedin_user(self):
        command = 'whoami'
        result = self.execute_command(command)

    # def parse_users(self, result):
    #     pass

    def helping_function(self):
        linux_new_dict = dict()
        for command, purpose in window_commands.items():
            print(f'{command} = {purpose}', end='\n')
            linux_new_dict[purpose] = str(command).lower()
        return linux_new_dict

    # def list_processes(self):
    #     "Centos related command"
    #
    # def install_package(self, package):
    #     pass
    #
    # def uninstall_package(self, package):
    #     pass
